### ISSUE TITLE
Is there a logrotate sink that supports archive existing log file on launch

### ISSUE THREAD

**Issue by xgdgsc** [KjellKod/g3sinks#100]
Currently it only appends to existing file and archive on reaching max size. Is it possible to add  an option to archive existing on launch?

**Comment by KjellKod** [comment]
That could be an option for sure. 
What would the trigger criteria be? 
- always do it?
- having a function in the sink that the user can call that triggers the archiving? 
- something else?

**Comment by xgdgsc** [comment]
Having a function call would suffice, I think.

**Comment by KjellKod** [comment]
It shouldn’t be too hard to add. I would suggest that you take a look at 

RotateLog: https://github.com/KjellKod/g3sinks/blob/master/logrotate/src/LogRotateHelper.ipp#L208

```

void LogRotateHelper::fileWrite(std::string message) {
   rotateLog();
   fileWriteWithoutRotate(message);
}



 bool LogRotateHelper::rotateLog() {
   std::ofstream& is(filestream());
   if (is.is_open()) {

      if (cur_log_size_ > max_log_size_) {
```

Maybe you could use this and adjust it slightly 



```

void LogRotateHelper::fileWrite(std::string message) {

if (cur_log_size_ > max_log_size_) {
     rotateLog();
}
   fileWriteWithoutRotate(message);
}

void LogRotateHelper::rotateLog() {
   std::ofstream& is(filestream());
   if (is.is_open()) {
   { ....
```

Then adding to LogRotate.h/cpp a function 
::rotateLog that just calls the helper function. Obviously unit tests etc needs updating too. 

This change request is not something that the community has asked for before so I’m not diving into it to fix it but I’m happy to guide you if you make a PR with that change
