### ISSUE TITLE
Windows file caching

### ISSUE THREAD

**Issue by clauderobi** [KjellKod/g3sinks#129]
Using Log Rotate

My problem is rather simple. On Windows, my log files as visible on the disk, remain at 0B until I close the program. (I guess if I waited long enough an had enough data the log Rotate would kick in and the file being closed Windows would flush on the disk).

I have no problem on Linux.

I do not touch to the flush_policy parameter and therefore it defaults to 1

I am not very familiar with Windows disk IO but is this a normal behaviour? I see that Microsoft has this function, FlushFileBuffers. Is this an indication that something must be added on top of std::flush? Would normally std::ofstream do the magic by itself?

I am cross compiling with mingw-w64. Is it the culprit?

**Comment by KjellKod** [comment]
It's not normal behavior. I don't recollect seeing this issue before and I know other folks are using mingw

**Comment by clauderobi** [comment]
Really weird...

I did a quick test in LogRotateHelper.ipp  using this 1 line modification and it works as expected...

void LogRotateHelper::fileWriteWithoutRotate(std::string message) {
   std::ofstream& out(filestream());
   out << message << std::flush;		// Just to test if on windows the entry would appear in the file in due time...
   flushPolicy();
   cur_log_size_ += message.size();
}

**Comment by clauderobi** [comment]
Ok I found the problem.... But it looks like a compiler fart!

In LogRotateHelper::LogRotateHelper(const std::string& log_prefix, const std::string& log_directory, size_t flush_policy)
   : log_file_with_path_(log_directory)
   , log_directory_(log_directory)
   , log_prefix_backup_(log_prefix)
   , outptr_(new std::ofstream)
   , steady_start_time_(std::chrono::steady_clock::now())
   , flush_policy_(flush_policy)
   , flush_policy_counter_(flush_policy) {

I changed the last argument name, flush_policy, to something else. I use fp. And it works.

Before doing this, I included flush_policy_counter_ in the output message. It started as 0, and then moved to -1, -2, etc. 

I also did a test in void LogRotateHelper::flushPolicy() to put the decrement in an else clause to the if and that worked too.

Really bizarre.

OTOH, definitely not related, but who knows. May I suggest you put everything in a namespace like you did for the main g3log library (which is great BTW)?

**Comment by KjellKod** [comment]
g3sinks is a collection of 3rd party sinks so it doesn't follow the coding/naming conventions used i g3log. Thanks for the praise and I do agree with the namespace usage (_happy to see a PR to change this for sure, but it won't be something I will drive on my own time_)
