### ISSUE TITLE
Various issues in windows

### ISSUE THREAD

**Issue by cstamatopoulos** [KjellKod/g3sinks#18]
3 compilation errors on windows in the ipp file
- strptime does not exist, maybe use the boost one or an open source implementation
- int buffer_size = 16184; (needs to be const)
    char buffer[buffer_size];
- std::string current_file(itr->path().filename().c_str()); for whatever reason it does not like it

the cmake needs quite a bit of love, zlib is missing, there is not ability to add debug and release for g3log and naming for the import lib is wrong for win. I got a cmake that works that I can share but it needs a 2nd set of eyes and make sure that all is good in the nix land

**Comment by KjellKod** [comment]
This sink is made for Linux only.

A potential, but lame, fix could be to have cmake refuse to build if not on the appropriate platform

**Comment by KjellKod** [comment]
If you a working fix I can review your pull request and also test it on Linux and OSX

**Comment by KjellKod** [comment]
@cstamatopoulos is this also taken care of to 100% in https://github.com/KjellKod/g3sinks/pull/23?

**Comment by cstamatopoulos** [comment]
Yes all has been taken care of.
I just saw itr->path().filename().c_str() was on this one as well, which was the last fix.
