### ISSUE TITLE
Remove boost system from cmake

### ISSUE THREAD

**Issue by cstamatopoulos** [KjellKod/g3sinks#26]
I dont see it anywhere being used.

**Comment by KjellKod** [comment]
Sounds good. The only boost library is used here: https://github.com/KjellKod/g3sinks/blob/master/logrotate/src/LogRotateUtility.cpp 

I have not, however checked if boost::filesystem depends on boost::system

**Comment by cstamatopoulos** [comment]
I think you might be right ! 
I was linking to system for other stuff so I never saw the linker error
Double checking.

**Comment by cstamatopoulos** [comment]
It seems that the 3 header files below are used, so you were correct
#include <boost/system/api_config.hpp>
#include <boost/system/error_code.hpp>
#include <boost/system/system_error.hpp>
