### ISSUE TITLE
LogRotate stops appending logs into a subfolder

### ISSUE THREAD

**Issue by d-led** [KjellKod/g3sinks#29]
Hi Kjell,

i've tried out the `LogRotate` appender in a little [project](https://github.com/d-led/crow_g3log_zmq). It did pack the first log file as expected, using the defaults, but then it didn't continue appending into a new file. Can it be that I'm using it [wrong](https://github.com/d-led/crow_g3log_zmq/blob/master/src/main.cpp#L52), or is it a bug? 

Cheers

**Comment by KjellKod** [comment]
How did you use it?

**Comment by d-led** [comment]
The code is as in the commit. I've loaded it with a constant stream of log messages. If you want, I can make an isolated repro program

**Comment by d-led** [comment]
update: it doesn't stop, but just doesn't put them into the configured folder ('logs' in my case), but in the `cwd` directory

**Comment by KjellKod** [comment]
Yes please , please give me a tiny code example that shows this behaviour.

**Comment by d-led** [comment]
```cpp
// g3log
#include <g3sinks/LogRotate.h>
#include <g3log/g3log.hpp>
#include <g3log/logworker.hpp>
#include <g3log/std2_make_unique.hpp>

#include <boost/filesystem.hpp>

int main(int argc, char* argv[]) {
	const char* path = "repro";
	boost::filesystem::path dir(path);
    boost::filesystem::create_directory(dir);

	std::unique_ptr<g3::LogWorker> worker(g3::LogWorker::createLogWorker());
	auto logger = worker->addSink(std2::make_unique<LogRotate>(argv[0], path),
                                  &LogRotate::save);
    g3::initializeLogging(worker.get());

    size_t count = 0;
    while(true) {
    	LOG(INFO) << std::to_string(count++) << std::endl;
    }
}
```

produces:
./repro/binlinuxgmakex32Releaseg3log_repro.log.2016-05-26-11-18-45.gz
./reprobinlinuxgmakex32Releaseg3log_repro.log

**Comment by KjellKod** [comment]
Perfect. Tx. I'm trying this now

**Comment by KjellKod** [comment]
I have confirmed the bug.

**Comment by KjellKod** [comment]
OK. So I don't have a fix for it yet but I have a workaround
If you change the filename, but set it to exactly the same name and the same folder the folder is the `""` then it works. 

I also changed "repro" to "repro/"


```
#include <g3sinks/LogRotate.h>
#include <g3log/g3log.hpp>
#include <g3log/logworker.hpp>
#include <g3log/std2_make_unique.hpp>

#include <boost/filesystem.hpp>
#include <iostream>

int main(int argc, char* argv[]) {
    const char* path = "repro/";
    boost::filesystem::path dir(path);
    boost::filesystem::create_directory(dir);

    std::unique_ptr<g3::LogWorker> worker(g3::LogWorker::createLogWorker());
    auto logger = worker->addSink(std2::make_unique<LogRotate>(argv[0], path),
                                  &LogRotate::save);
    g3::initializeLogging(worker.get());

     logger->call(&LogRotate::changeLogFile, path, "").wait();
     std::cout << "logging to: " << logger->call(&LogRotate::logFileName).get() << std::endl;

    size_t count = 0;
    while(true) {
        LOG(INFO) << std::to_string(count++) << std::endl;
    }
}
```

**Comment by KjellKod** [comment]
@d-led it seems the directory has to end with a "/" or else this bug appears. 
I will have a fix for it but for now a second work around would be to have `repro` --> `repro/`. That should be enough to make it work. 

Can you please confirm?

**Comment by d-led** [comment]
it works this way, thanks!

**Comment by KjellKod** [comment]
@d-led please review https://github.com/KjellKod/g3sinks/pull/30

**Comment by KjellKod** [comment]
@craig-cogdill, @john-gress, please review https://github.com/KjellKod/g3sinks/pull/30

**Comment by KjellKod** [comment]
Fixed in https://github.com/KjellKod/g3sinks/pull/30
