### ISSUE TITLE
Visual Studio 2013, Chrono issue in logrotatehelper.ipp

### ISSUE THREAD

**Issue by ppedro74** [KjellKod/g3sinks#33]
error C2664: 'std::chrono::time_point<std::chrono::steady_clock,std::chrono::system_clock::duration>::time_point(const std::chrono::time_point<std::chrono::steady_clock,std::chrono::system_clock::duration> &)' : cannot convert argument 1 from 'std::chrono::system_clock::time_point' to 'const std::chrono::system_clock::duration &'	c:\cpp\g3sinks\logrotate\src\logrotatehelper.ipp	90	

line:
steady_start_time_(std::chrono::steady_clock::now())

I'm not familiar with chrono, can you help  ?

**Comment by KjellKod** [comment]
It sounds like the platform you are on does not support fully C++11

**Comment by ppedro74** [comment]
Visual Studio 2013, 2015. Msft says yes... :) but must be something related to msft chrono implementation, if you any idea.

**Comment by KjellKod** [comment]
I suggest makin a simple hello world project to verify that it works for you in the VS2013 environment. There are many that use g3log in VS2015 but I am not sure about 2013 and I have no easy way of installing VS2013 to see if it works

**Comment by KjellKod** [comment]
I.e the simple hello world should verify chrone without any g3log.

**Comment by KjellKod** [comment]
No action. No support for VS2013 from me since I don't have a Windows computer. 
If the community wants this then please resolve this through pull requests
