### ISSUE TITLE
static_assert failure for Logrotate

### ISSUE THREAD

**Issue by cstamatopoulos** [KjellKod/g3sinks#35]
It seems that I am hitting the above static_assert in msvc 2015
`static_assert(0 < sizeof (_Ty),
			"can't delete an incomplete type");`

It is happening at virtual ~Sink()  which then calls 
`std::unique_ptr<LogRotate,std::default_delete<LogRotate>>::~unique_ptr<LogRotate,std::default_delete<LogRotate> >() `

**Comment by cstamatopoulos** [comment]
I wonder if that static_assert is a new change that was introduced in a recent update since there has not been any in the g3sinks, except for some readme files...

**Comment by cstamatopoulos** [comment]
Well it seems that the fix for %f6 somehow fixes this one as well.
I really dont know why that static_assert was thrown if that was the case....
I will confirm again once the pull request is merged and close it then.

**Comment by KjellKod** [comment]
I have not merged the g3log pull request because I found some inconsistencies in g3sinks regarding how it's built and specifically how the library is named and expectations of library naming (g3sinks side towards g3log). This is an issue on especially Windows and OSX

I'm just swamped with work + Elk hunting for 2 more weeks so I don't know when I can get to it

**Comment by cstamatopoulos** [comment]
I lost you there ! The time formatting pull request had no changes related to how g3sinks is built.
I am confused with the pull request that you are mentioning here.

Regardless, after the last pull request that fixes the time formatting issue, the issue I mentioned here is also fixed. Closing this even though I dont know why that static_assert was hit.

**Comment by KjellKod** [comment]
You are right. What I man is that I couldn't confirm the fix on all platforms on g3sinks due to the build issue
