### ISSUE TITLE
rm -f does not work on windows

### ISSUE THREAD

**Issue by cstamatopoulos** [KjellKod/g3sinks#36]
The deletion of files in RotateFileTest.h should be changed to something like this.
Unless you want to use `<filesystem>` which is already in msvc

```
#if (defined(WIN32) || defined(_WIN32) || defined(__WIN32__)) && !defined(__MINGW32__)
  std::string removeTgz_1 = _directory + "g3sink_rotatefile_test*.gz";
  remove(removeTgz_1.c_str());

  std::string removeTgz_2 = _directory + "new_sink_name*.gz";
  remove(removeTgz_2.c_str());
#else
  std::string removeTgz_1 = std::string("rm -f ") + _directory + "g3sink_rotatefile_test*.gz";
  system(removeTgz_1.c_str());

  std::string removeTgz_2 = std::string("rm -f ") + _directory + "new_sink_name*.gz";
  system(removeTgz_2.c_str());
#endif
```

**Comment by KjellKod** [comment]
Thanks

Does can you use 
unlink(..), remove(...) on Windows? 
Else "rmdir" could be used.

For Linux unlink or remove should be used. Or something similar to:

**Comment by KjellKod** [comment]
FYI: I'm looking into addressing this by using std::filesystem and seeing if the support is good enough in Linux. (It should just work on Windows).

**Comment by KjellKod** [comment]
closed by https://github.com/KjellKod/g3sinks/pull/124
