### ISSUE TITLE
Bring across the git version extraction from g3log to support windows as well

### ISSUE THREAD

**Issue by cstamatopoulos** [KjellKod/g3sinks#47]
I could do a pull request but it is probably quicker for you to just copy paste that part

**Comment by KjellKod** [comment]
Thanks for the nudge. Yes. I'll do that

**Comment by cstamatopoulos** [comment]
@KjellKod Maybe it is not worth doing.
I think the cmake build needs a few fixes for this to build fine in windows.
It is pretty hard as it is now to specify the headers of g3logger as well as the include path of boost.
My current hack from command line is by specifying the below definitions which are not accesible from gui

> -DBoost_INCLUDE_DIR=../path_to_/boost-headers/
> -DCMAKE_PREFIX_PATH=../path_to_/g3log-static/

However if you link dynamically to boost in windows you also need
> DBOOST_ALL_DYN_LINK
so that you link to the import lib filename of  boost_* rather than the libboost_* lib

I will be able to probably send you a pull request next week.

**Comment by cstamatopoulos** [comment]
The attached file tries to have as minimal changes as possible and should cause no issues or changes to *NIX.
You can have a look at it but made small changes to:
- add version extraction from g3log
- add G3_LOGGER_INCLUDE_PATH variable for the header path of g3logger
- add G3_LOGGER_LIB_PATH variable to specify search path for g3logger
- add separate BOOST_SEARCH_PATH variable to specify search path for g3logger
- add BOOST_INCLUDE to specify boost include path
- add BOOST_ALL_DYN_LINK to support dynamic linking to boost, off by default

[CMakeLists.txt](https://github.com/KjellKod/g3sinks/files/988213/CMakeLists.txt)

**Comment by KjellKod** [comment]
Interesting.

In OSX and Linux boost is found automatically.

I think It's time to put up cloud CI for g3sinks as well.

**Comment by cstamatopoulos** [comment]
I wish that was the case in Windows land ! 
I think I had some success in the past by setting the Boost_Root or BOOST_DIR manually.
I could it give it a try again but I think it still depends on how the package is sorted.
E.g. some use nuget packages so having the ability to specify the options manually is always good.
