### ISSUE TITLE
TARGET_INCLUDE_DIRECTORIES should also mention generated files directory

### ISSUE THREAD

**Issue by MaxSavenkov** [KjellKod/g3sinks#55]
In Build.cmake the last line should be

```
TARGET_INCLUDE_DIRECTORIES(${G3LOG_LIBRARY} PUBLIC ${LOG_SRC} "${CMAKE_CURRENT_BINARY_DIR}/include")
```

so that g3log can be used in CMake-based project via add_subdirectory/target_link_library (presently, if you do this, the build would break because it can't find generated definitions).

Also the comment "# Kjell: This is likely not necessary, except for Windows?" is somewhat incorrect, since a CMake-based project on any system would benefit from having library's include directory exported if g3log is not installed, but instead is used as a sub-project.

**Comment by MaxSavenkov** [comment]
Uh, sorry, I somehow created this issue in the wrong project. My bad :(

I created a pull request for g3log: https://github.com/KjellKod/g3log/pull/268

**Comment by KjellKod** [comment]
closed it's resolved in your PR. Thanks @MaxSavenkov
