### ISSUE TITLE
white should be 37 rather than 97

### ISSUE THREAD

**Issue by guzhaoyuan** [KjellKod/g3sinks#58]
In snippets/ColorCoutSink.hpp, you labelled white color as 97, which is kind of dark and grey.
According to https://stackoverflow.com/questions/2616906/how-do-i-output-coloured-text-to-a-linux-terminal, white font should be 37.

**Comment by KjellKod** [comment]
Thanks. 

It’s really just a code snippet example. If you want to get it whiter please put up a PR
