### ISSUE TITLE
Build errors on Ubuntu 16.04.

### ISSUE THREAD

**Issue by surfbytes** [KjellKod/g3sinks#61]
Hello,

I have been using g3log and just tried to build the logrotate sync and am getting build errors (below).
I followed the readme and noticed that the boost include dir directive should be Boost_INCLUDE_DIRS and not Boost_INCLUDE_DIR as stated in the readme.

Once I got that sorted out I see the build errors below.
I am building on Ubuntu 16.04 with gcc 5.4.0 .

Thanks for any help, I need log rotation or at least some method of limiting log size.

-Randy

`etg@ubuntu:~/g3sinks/logrotate$ make -j
[ 25%] Building CXX object CMakeFiles/g3logrotate.dir/src/LogRotate.cpp.o
[ 25%] Building CXX object CMakeFiles/g3logrotate.dir/src/LogRotateUtility.cpp.o
[ 25%] Building CXX object CMakeFiles/g3logrotate.dir/src/LogRotateWithFilter.cpp.o
In file included from /home/etg/g3sinks/logrotate/src/LogRotateWithFilter.cpp:11:0:
/home/etg/g3sinks/logrotate/src/g3sinks/LogRotateWithFilter.h:44:45: error: ‘g3::LogMessage::LogDetailsFunc’ has not been declared
     void overrideLogDetails(g3::LogMessage::LogDetailsFunc func);
                                             ^
/home/etg/g3sinks/logrotate/src/g3sinks/LogRotateWithFilter.h:52:21: error: ‘LogDetailsFunc’ in ‘struct g3::LogMessage’ does not name a type
     g3::LogMessage::LogDetailsFunc _log_details_func;
                     ^
/home/etg/g3sinks/logrotate/src/LogRotateWithFilter.cpp: In constructor ‘LogRotateWithFilter::LogRotateWithFilter(LogRotateWithFilter::LogRotateUniquePtr, LogRotateWithFilter::IgnoreLogLevelsFilter)’:
/home/etg/g3sinks/logrotate/src/LogRotateWithFilter.cpp:29:7: error: class ‘LogRotateWithFilter’ does not have any field named ‘_log_details_func’
     , _log_details_func(&g3::LogMessage::DefaultLogDetailsToString)
       ^
/home/etg/g3sinks/logrotate/src/LogRotateWithFilter.cpp:29:26: error: ‘DefaultLogDetailsToString’ is not a member of ‘g3::LogMessage’
     , _log_details_func(&g3::LogMessage::DefaultLogDetailsToString)
                          ^
/home/etg/g3sinks/logrotate/src/LogRotateWithFilter.cpp: In member function ‘void LogRotateWithFilter::save(g3::LogMessageMover)’:
/home/etg/g3sinks/logrotate/src/LogRotateWithFilter.cpp:41:45: error: ‘_log_details_func’ was not declared in this scope
       _logger->save(logEntry.get().toString(_log_details_func));
                                             ^
/home/etg/g3sinks/logrotate/src/LogRotateWithFilter.cpp: At global scope:
/home/etg/g3sinks/logrotate/src/LogRotateWithFilter.cpp:94:62: error: variable or field ‘overrideLogDetails’ declared void
 void LogRotateWithFilter::overrideLogDetails(g3::LogMessage::LogDetailsFunc func) {
                                                              ^
/home/etg/g3sinks/logrotate/src/LogRotateWithFilter.cpp:94:46: error: ‘LogDetailsFunc’ is not a member of ‘g3::LogMessage’
 void LogRotateWithFilter::overrideLogDetails(g3::LogMessage::LogDetailsFunc func) {
                                              ^
CMakeFiles/g3logrotate.dir/build.make:110: recipe for target 'CMakeFiles/g3logrotate.dir/src/LogRotateWithFilter.cpp.o' failed
make[2]: *** [CMakeFiles/g3logrotate.dir/src/LogRotateWithFilter.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/g3logrotate.dir/all' failed
make[1]: *** [CMakeFiles/g3logrotate.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
etg@ubuntu:~/g3sinks/logrotate$ gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

`

**Comment by KjellKod** [comment]
Thanks. Please put up a PR if you don’t mind!

**Comment by KjellKod** [comment]
I have not been able to reproduce the build error. Please put up a PR correction
