### ISSUE TITLE
Build error when CMAKE_PREFIX_PATH is a list

### ISSUE THREAD

**Issue by circum1** [KjellKod/g3sinks#62]
I try to build g3sinks on linux in a project where every component is installed to its separate location, what means that CMAKE_PREFIX_PATH variable is a list with more than one items. 

The problem is that if I try to build g3sinks/logrotate with the following command:

`cmake -DCMAKE_PREFIX_PATH="/usr/local/somedir;/usr/local/otherdir"  .....`

Cmake fails with the following error:

```
CMake Error at CMakeLists.txt:67 (IF):
  if given arguments:

    "/usr/local/somedir" "/usr/local/otherdir.x" "STREQUAL" ".x"

  Unknown arguments specified
```

I tried to fix that by changing the offending line:

```
@@ -64,15 +64,17 @@ INCLUDE (${LogRotate_SOURCE_DIR}/Options.cmake)
 # Find all libraries
 #
 
- IF (${CMAKE_PREFIX_PATH}.x STREQUAL ".x")
+ IF (NOT DEFINED CMAKE_PREFIX_PATH)
     SET(CMAKE_PREFIX_PATH /usr/local)
     MESSAGE("CMAKE_PREFIX_PATH: " ${CMAKE_PREFIX_PATH})
  ENDIF()
```

Then cmake runs successfully, but unfortunately the g3log include files are not found during compile because g3sinks adds the include directory like this:

`include_directories(${CMAKE_PREFIX_PATH}/include)`

what, obviously, is not correct when CMAKE_PREFIX_PATH is a list.

Do I miss something about cmake (that is for sure :)), or is it really a flaw in g3sink's cmake setup? I have not much knowledge about cmake, and have access only to linux machine, so I am not the best person to create a PR, but if it helps I can try to fix it using find_package() to load g3loggerConfig.cmake, using G3LOG_LIBRARY and G3LOG_INCLUDE_DIR defined there, and testing on my machine.

**Comment by KjellKod** [comment]
Lol. I guess it’s a new for everything. It sounds great with a PR. Looking forward to it. 

I don’t know what reasons you have for using separate locations but it seems very “odd”. Not following best practices for library installations on Linux. 

Regardless it sounds good with a PR

**Comment by KjellKod** [comment]
closed due to lack of response
