### ISSUE TITLE
Sink for Microsoft TraceLogging

### ISSUE THREAD

**Issue by jjhegedus** [KjellKod/g3sinks#69]
I've included a sink for Microsoft's TraceLogging below.  It is simple but works.  This is useful for logging from Windows UWP apps.  I'm using it with my HoloLens code.

I'm offering it up for integration into g3sinks if you are interested.  I would have created a pull request but I'm not entirely sure how best to set it up to integrate with your approach on g3sinks.  I am interested in learning how best to do that if you are willing to provide a little guidance.

I will also be creating a sink for logging on the MagicLeap.  My hope was that I could get some guidance about the approach on this sink, especially insight on setting up CMake, since I've never used it, and then leverage that knowledge to create a pull request for the MagicLeap logger.

```
#pragma once
#include <g3log/logmessage.hpp>

// Trace Logging
#include <TraceLoggingProvider.h>

TRACELOGGING_DECLARE_PROVIDER(traceProvider);

#define TraceLogWrite(eventName, ...) \
    _TlgWrite_imp(_TlgWrite, \
    traceProvider, eventName, \
    (NULL, NULL), \
    __VA_ARGS__)

// *** BEGIN EXAMPLE CLIENT TRACELOGGING DEFINITION ***
// REQUIRES CLIENT TRACELOGGING DEFINITION AS BELOW
// Typically Performed at the top of your main file
//#include <TraceLoggingProvider.h>
//
//TRACELOGGING_DEFINE_PROVIDER(
//  traceProvider,
//  "ndtech",
//  // {c78f9e8e-2e05-5320-8f4e-7bd922ecb3a0}
//  (0xc78f9e8e, 0x2e05, 0x5320, 0x8f, 0x4e, 0x7b, 0xd9, 0x22, 0xec, 0xb3, 0xa0));
// *** END EXAMPLE CLIENT TRACELOGGING DEFINITION ***

// *** BEGIN EXAMPLE CLIENT USAGE ***
//// Typically performed immediately in the main function
//// First you register the traceProvider declared above
//TraceLoggingRegister(traceProvider);
//using namespace g3;
//std::unique_ptr<LogWorker> logworker{ LogWorker::createLogWorker() };
//auto sinkHandle = logworker->addSink(std::make_unique<g3logTracelogging>(),
//  &g3logTracelogging::ReceiveLogMessage);
//
//// initialize the logger before it can receive LOG calls
//initializeLogging(logworker.get());
//LOG(WARNING) << "g3logTracelogging test: This log call, may or may not happend before"
//<< "the sinkHandle->call below";
// *** BEGIN EXAMPLE CLIENT USAGE ***

struct g3logTracelogging {

  void ReceiveLogMessage(g3::LogMessageMover logEntry) {
    auto level = logEntry.get()._level;

    TraceLogWrite(
      "g3logTracelogging",
      TraceLoggingString(logEntry.get().level().c_str(), "LOG_LEVEL"),
      TraceLoggingString(logEntry.get().threadID().c_str(), "THREAD_ID"),
      TraceLoggingString(logEntry.get().timestamp().c_str(), "TIME_STAMP"),
      TraceLoggingString(logEntry.get().file().c_str(), "FILE"),
      TraceLoggingString(logEntry.get().file_path().c_str(), "FILE_PATH"),
      TraceLoggingString(logEntry.get().function().c_str(), "FUNCTION"),
      TraceLoggingString(logEntry.get().message().c_str(), "MESSAGE"));
  }
};
```

**Comment by KjellKod** [comment]
Awesome. So far we don’t have any pure Windows sinks 

G3sinks is, as you already probably noticed, a collection of sinks. There is no “root” build location but has directories with separate build systems. 

Thanks to this It is more lax in the requirements (compared to G3log) and the sinks do not have to be cross-platform. 

I suggest looking at the two directories syslog or logRotate and see how the CMake structures are 

My recommendation - that you don’t have to follow to 100% - it’s just a recommendation is to : 

1. Fork g3sinks repo. Create a separate branch on your rep clone
2. Create your own directory for this sink
3. Create a README.md and explain what it is and how to use it
4. Create an example directory with a simple main.cpp and a CMake file - consider this the go to place for people that want to quickly use your sink
5. I’m a huge fan of TDD and if nothing else, at least basic test coverage to ensure nothing breaks your sink if someone wants to add changes to it. I would recommend to create a test directory also. See logRotate and how the gtest is incorporated in the repo and used with logRotate
6. Add a src directory etc with CMake file in the root of your sink directory. 
7. Please! Don’t forget to add a section to https://github.com/KjellKod/g3sinks/blob/master/scripts/buildAndRunTests.sh for your sink. IF your sink is Windows only then please create a new build-and-test script and I can set it up to be built and tested on a Windows cloud CI



I.e follow the concept of logRotate (ambitious) or at least the syslogSetup and you will do fine.  

Remember the purpose isn’t to follow some stringent rules by me but to make it super easy for someone to get up and running with your sink in as little time as possible (while still having good code quality for future changes). 

If you think of a better model to build and incorporate your sink you are welcome to use that model!

**Comment by KjellKod** [comment]
If your sink is too har to build independently due to requirement to link with the `TraceLogging` then maybe the following would be a better setup? 
Steps 1-4 above but possibly without/without CMake build? 

Not sure what the best approach is here. If it can’t be built without access to the `Trace` library then it can still provide value to the community as long as it’s clear how people can integrate it. I.e a Readme+ possibly a CMake or similar file *even if* the CMake isn’t to be used on a cloud CI

**Comment by jjhegedus** [comment]
Thanks for the step by step.  I'll give it a shot and see what I can come up with.  Once again, I can't tell you how much I appreciate your responsiveness.

**Comment by jjhegedus** [comment]
Sadly, I'm already running into my first bit of confusion.  As you mentioned, linking with TraceLogging is required, but that part isn't difficult.  However, in order to get this to work with the HoloLens (really any UWP project) and the Magic Leap Emulator for Windows, I resorted to making a special build for g3log as well as use a special build system based on Visual Studio and Magic Leap's Mabu builder (https://creator.magicleap.com/learn/guides/magic-leap-builder-overview requires signup).  It may not have been necessary, but it was the best I could come up with at the moment.  I've put both on GitHub at https://github.com/jjhegedus/g3log-holo and https://github.com/jjhegedus/g3log_tracelogging.  These are working for my use case but I'm struggling a bit with how they should map into your repository here.  I would rather publish them here if possible and practical because I think it will be best for all to keep them together to build momentum and visibility.

g3log_tracelogging is intended to be Windows only.  The g3log_holo build will be required by the g3log_magic_leap sink that I am working on so it will also need to build for and run on the MagicLeap device which runs a Linux variant.  Probably need to rename it. ;-)  My intent is to use g3log as a front end for all logging in the framework, both for the HoloLens and the Magic Leap as well as for any additional devices I add support for in the future.

Any additional thoughts you have on how best to stay in alignment while making it as easy as possible for others to consume would be greatly appreciated.  I'll warn in advance that I will probably not be quite as responsive as you are today because it is my father's birthday and we have people coming over for a party in a few hours.

**Comment by KjellKod** [comment]
Think over my 2nd suggestion. If it is too cumbersome to link you can always create instructions for how to use it. The build system, if you add it, can be unique for your sink as long as there are clear steps for users that want to adopt it

**Comment by jjhegedus** [comment]
I may have to go that way eventually but I am going to try to work through the process.  I am still struggling with the basics of CMake.  I forked this repo and created a branch at https://github.com/jjhegedus/g3sinks/tree/tracelogging per your instructions.  I also created a folder for the tracelogging sink.  I've been working to get initial step of building the version of g3log that works with the HoloLens and MagicLeap built.  It really wasn't too hard for me to get working without CMake but I'm struggling to translate it to CMake.  Something must be wrong with my setup because cmake can't find g3logger.  I copied your code from the syslog sink.

```
# search for g3log
find_package(g3logger REQUIRED)
# add the missing target if needed
if (NOT TARGET g3logger)
    add_library(g3logger SHARED IMPORTED)
    find_package(Threads REQUIRED)
    set_target_properties(g3logger PROPERTIES
        INTERFACE_INCLUDE_DIRECTORIES "${G3LOG_INCLUDE_DIRS}"
        IMPORTED_LOCATION "${G3LOG_LIBRARY}"
        IMPORTED_LINK_INTERFACE_LIBRARIES  Threads::Threads
        )
endif()
```

Here is the command line I'm running

`c:\Projects\third-party\forks\g3sinks\tracelogging>cmake -DCMAKE_PREFIX_PATH=C:/Projects/third-party/g3log`

C:/Projects/third-party/g3log is the root folder where I cloned this repo but I'm getting the error below

```
CMake Error at C:/Program Files/CMake/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find g3logger (missing: G3LOG_LIBRARY)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  C:/Projects/third-party/g3log/cmake/g3loggerConfig.cmake:45 (find_package_handle_standard_args)
  CMakeLists.txt:16 (find_package)


-- Configuring incomplete, errors occurred!
See also "C:/Projects/third-party/forks/g3sinks/tracelogging/CMakeFiles/CMakeOutput.log".
See also "C:/Projects/third-party/forks/g3sinks/tracelogging/CMakeFiles/CMakeError.log".

c:\Projects\third-party\forks\g3sinks\tracelogging>notepad C:/Projects/third-party/forks/g3sinks/tracelogging/CMakeFiles/CMakeError.log
```

I'll keep working on it but if you see anything obvious, I'd appreciate any pointers you can give me.

**Comment by KjellKod** [comment]
I think you want the directory where the G3log library is, not the repo. 

I.e is it installed somewhere? If not, is it built so the library and header files can be reached?

**Comment by jjhegedus** [comment]
Ah, that helps.  I manually copied the build output and the include files into a structure that mirrors the expectation on Linux and used that folder as the CMAKE_PREFIX_PATH.  That got me past the next step but a few more steps to go.

Sorry for all the dumb questions and thank you for your help.

**Comment by jjhegedus** [comment]
Closing this thread in favor of pull request #71
