### ISSUE TITLE
syslog/test folder seems to be copy of the example folder

### ISSUE THREAD

**Issue by mkilivan** [KjellKod/g3sinks#95]
`syslog/example/main.cpp` and `syslog/test/main.cpp` seems almost the same. What is the purpose of the test folder?

**Comment by KjellKod** [comment]
@JoelStienlet @michaelbgratton

**Comment by JoelStienlet** [comment]
Perhaps the test should be improved, for example by checking that the strings have actually all been sent to the system log? (Better do this in a script than manually.) We could add this to the script calling the tests. For example on linux with journald:
`journalctl | grep "Hi log 123"`
The same with all other strings from the test to make sure none is missing.
and
`syslog -C | grep "Hi log 123"`
on macos?

**Comment by mkilivan** [comment]
Also note that the source code in the test folder is not a test, it is an example.

**Comment by JoelStienlet** [comment]
I think the test should be changed into a proper test, perhaps by rewriting a proper test from scratch? A test can catch some basic problems ( like the one I've encountered when the size of the strings caused syslog's buffer to be reallocated ), you can quickly see if a change from a PR has caused something to break. But it should really test corner cases and unusual values, and as it is, @mkilivan is right, it is not doing anything more than the example actually.
